name: Balsa Continuous Integration

on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "**.cpp"
      - "**.hpp"
      - "**.hxx"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "**.cpp"
      - "**.hpp"
      - "**.hxx"

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Meson v${{ matrix.meson_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        meson_version: ["1.5.2"] #["1.2.0", "1.3.0", "1.4.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Linux dependencies
        run: |
          if [ "$RUNNER_OS" == "LinuX" ]; then
          apt install libgl-dev libgl1-mesa-dev
          fi


      - name: Install dependencies
        run: python -m pip install meson==${{ matrix.meson_version }} ninja

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 2.8.1

      - name: Conan profile creation
        run: | 
          conan profile detect

      - name: Conan dependencies
        run: conan install . --output-folder=build --build=missing # prepare conan

      - name: Configure Project
        run: meson setup --native-file build/conan_meson_native.ini . build
        env:
          CC: gcc

      - name: Run Tests
        run: meson test -C builddir/ -v

      - name: Upload Test Log
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.os }}_Meson_Testlog
          path: builddir/meson-logs/testlog.txt
